adversary A : () -> ().
oracle Orcl : () -> ().

bound_succ [
  let x1 = ();
  let x2 = ();
  let x3 = ();
  let x4 = ();
  let x5 = ();
  let x6 = ();
  let x7 = ();
  x8 <- A() with
    Orcl() = {
      let y1 = ();
      let y2 = ();
      let y3 = ();
      let y4 = ();
      let y5 = ();
      let y6 = ();
      let y7 = ();
      return ();
    };
] : x1 = x7.
move [1 3] +4.   restart. (* move range from 1 to 3 *)
case_ev (true).

move [x1 x3] x7. restart.

///=.